import { Bebas_Neue, Archivo } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ShopContextProvider } from '../contexts/ShopContext';


const bebasNeue = Bebas_Neue({
  variable: "--bebas_neue",
  subsets: ["latin"],
  weight: "400",
});

const archivo = Archivo({
  variable: "--archivo",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${archivo.variable} antialiased`}>
        <ShopContextProvider> 
        <Navbar />
        <div className="flex-1">{children}</div>
        <Footer />
        </ShopContextProvider>
      </body>
    </html>
  );
}
